/**
 * KYC Document Requirements Configuration
 * Extracted from kyc_document.md
 * Provides default document requirements for each entity type
 */

export const DEFAULT_KYC_REQUIREMENTS = {
  INDIVIDUAL: [
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID', isRequired: true },
    { documentType: 'KRA_PIN', description: 'KRA PIN Certificate', isRequired: true },
    { documentType: 'PROOF_OF_ADDRESS', description: 'Proof of Address', isRequired: true },
    { documentType: 'PASSPORT_PHOTO', description: 'Passport Photo', isRequired: true },
  ],
  SOLE_PROPRIETOR: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID', isRequired: true },
    { documentType: 'KRA_PIN', description: 'KRA PIN Certificate', isRequired: true },
    { documentType: 'CERTIFICATE_OF_REGISTRATION', description: 'Certificate of Registration', isRequired: true },
    { documentType: 'BANK_STATEMENT', description: 'Copy of cancelled cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
  ],
  PARTNERSHIP: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID', isRequired: true },
    { documentType: 'DIRECTORS_KRA_PIN', description: 'Kenyan Directors KRA PIN Certificates', isRequired: true },
    { documentType: 'CERTIFICATE_OF_REGISTRATION', description: 'Certificate of Registration', isRequired: true },
    { documentType: 'COMPANY_KRA_PIN', description: 'Partnership KRA PIN / Company KRA PIN Certificate', isRequired: true },
    { documentType: 'PESAPAL_AUTHORIZATION', description: 'Letter Authorizing Entry with Pesapal', isRequired: true },
    { documentType: 'BANK_STATEMENT', description: 'Copy of cancelled cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
  ],
  LIMITED_LIABILITY_COMPANY: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID', isRequired: true },
    { documentType: 'DIRECTORS_SHAREHOLDERS_KRA_PIN', description: 'Kenyan Directors and Shareholders KRA PIN Certificates', isRequired: true },
    { documentType: 'CERTIFICATE_OF_INCORPORATION', description: 'Certificate of Incorporation', isRequired: true },
    { documentType: 'COMPANY_KRA_PIN', description: 'Company KRA PIN Certificate', isRequired: true },
    { documentType: 'CR12', description: 'Current CR12 (Validity: 1 Year)', isRequired: true },
    { documentType: 'PESAPAL_AUTHORIZATION', description: 'Letter Authorizing Entry with Pesapal', isRequired: true },
    { documentType: 'BANK_STATEMENT', description: 'Copy of Cancelled Cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
  ],
  LIMITED_LIABILITY_PARTNERSHIP: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID', isRequired: true },
    { documentType: 'DIRECTORS_SHAREHOLDERS_KRA_PIN', description: 'Kenyan Directors and Shareholders KRA PIN Certificates', isRequired: true },
    { documentType: 'CERTIFICATE_OF_INCORPORATION', description: 'Certificate of Incorporation / Certificate of Registration', isRequired: true },
    { documentType: 'COMPANY_KRA_PIN', description: 'Company KRA PIN Certificate', isRequired: true },
    { documentType: 'CR13', description: 'Current CR13', isRequired: true },
    { documentType: 'PESAPAL_AUTHORIZATION', description: 'Letter Authorizing Entry with Pesapal', isRequired: true },
    { documentType: 'BANK_STATEMENT', description: 'Copy of Cancelled Cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
  ],
  EMPLOYMENT_AGENCY_LLC: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID', isRequired: true },
    { documentType: 'DIRECTORS_SHAREHOLDERS_KRA_PIN', description: 'Kenyan Directors and Shareholders KRA PIN Certificates', isRequired: true },
    { documentType: 'CERTIFICATE_OF_INCORPORATION', description: 'Certificate of Incorporation', isRequired: true },
    { documentType: 'COMPANY_KRA_PIN', description: 'Company KRA PIN Certificate', isRequired: true },
    { documentType: 'CR12', description: 'Current CR12 (Validity: 1 Year)', isRequired: true },
    { documentType: 'PESAPAL_AUTHORIZATION', description: 'Letter Authorizing Entry with Pesapal', isRequired: true },
    { documentType: 'BANK_STATEMENT', description: 'Copy of Cancelled Cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
    { documentType: 'EMPLOYMENT_AGENCY_LICENSE', description: 'Certified Copy of Institution\'s License from National Employment Agency', isRequired: true },
  ],
  FOREIGN_COMPANY_COMPLIANCE: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID (At least 2)', isRequired: true },
    { documentType: 'DIRECTORS_SHAREHOLDERS_KRA_PIN', description: 'Kenyan Directors and Shareholders KRA PIN Certificates', isRequired: true },
    { documentType: 'CERTIFICATE_OF_COMPLIANCE', description: 'Certificate of Incorporation / Company Certificate of Compliance', isRequired: true },
    { documentType: 'COMPANY_KRA_PIN', description: 'Company KRA PIN Certificate', isRequired: true },
    { documentType: 'CR12', description: 'Current CR12 (Validity: 1 Year)', isRequired: true },
    { documentType: 'PESAPAL_AUTHORIZATION', description: 'Letter Authorizing Entry with Pesapal', isRequired: true },
    { documentType: 'BANK_STATEMENT', description: 'Copy of Cancelled Cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
  ],
  PRIVATE_HOSPITAL_SOLE_PROPRIETOR: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID', isRequired: true },
    { documentType: 'KRA_PIN', description: 'KRA PIN Certificate', isRequired: true },
    { documentType: 'CERTIFICATE_OF_REGISTRATION', description: 'Certificate of Registration', isRequired: true },
    { documentType: 'BANK_STATEMENT', description: 'Copy of Cancelled Cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
    { documentType: 'HEALTH_LICENSE', description: 'Ministry of Health License / License from KMPDB', isRequired: true },
  ],
  PRIVATE_HOSPITAL_LLC: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID', isRequired: true },
    { documentType: 'DIRECTORS_SHAREHOLDERS_KRA_PIN', description: 'Kenyan Directors and Shareholders KRA PIN Certificates', isRequired: true },
    { documentType: 'CERTIFICATE_OF_INCORPORATION', description: 'Certificate of Incorporation', isRequired: true },
    { documentType: 'COMPANY_KRA_PIN', description: 'Company KRA PIN Certificate', isRequired: true },
    { documentType: 'CR12', description: 'Current CR12 (Validity: 1 Year)', isRequired: true },
    { documentType: 'PESAPAL_AUTHORIZATION', description: 'Letter Authorizing Entry with Pesapal', isRequired: true },
    { documentType: 'BANK_STATEMENT', description: 'Copy of Cancelled Cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
    { documentType: 'HEALTH_LICENSE', description: 'Ministry of Health License / License from KMPDB', isRequired: true },
  ],
  PUBLIC_HOSPITAL: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID (At least 2)', isRequired: true },
    { documentType: 'SIGNATORIES_KRA_PIN', description: 'Signatories KRA PIN Certificate', isRequired: true },
    { documentType: 'CERTIFICATE_OF_REGISTRATION', description: 'Certificate of Registration', isRequired: true },
    { documentType: 'HOSPITAL_KRA_PIN', description: 'Hospital KRA PIN Certificate', isRequired: true },
    { documentType: 'BANK_STATEMENT', description: 'Copy of Cancelled Cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
    { documentType: 'PESAPAL_AUTHORIZATION', description: 'Letter Authorizing Entry with Pesapal', isRequired: true },
    { documentType: 'COUNTY_AUTHORIZATION', description: 'Contract Form Signed by Authorized Signatory within County Health Department', isRequired: true },
  ],
  PRIVATE_EDUCATION_SOLE_PROPRIETOR: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID', isRequired: true },
    { documentType: 'KRA_PIN', description: 'KRA PIN Certificate', isRequired: true },
    { documentType: 'CERTIFICATE_OF_REGISTRATION', description: 'Certificate of Registration', isRequired: true },
    { documentType: 'SCHOOL_KRA_PIN', description: 'School KRA PIN Certificate', isRequired: true },
    { documentType: 'BANK_STATEMENT', description: 'Copy of Cancelled Cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
    { documentType: 'EDUCATION_LICENSE', description: 'Copy of Ministry of Education License or Certification', isRequired: true },
  ],
  PRIVATE_EDUCATION_LLC: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID', isRequired: true },
    { documentType: 'DIRECTORS_SHAREHOLDERS_KRA_PIN', description: 'Kenyan Directors and Shareholders KRA PIN Certificates', isRequired: true },
    { documentType: 'CERTIFICATE_OF_INCORPORATION', description: 'Certificate of Incorporation', isRequired: true },
    { documentType: 'COMPANY_KRA_PIN', description: 'Company KRA PIN Certificate', isRequired: true },
    { documentType: 'CR12', description: 'Current CR12 (Validity: 1 Year)', isRequired: true },
    { documentType: 'PESAPAL_AUTHORIZATION', description: 'Letter Authorizing Entry with Pesapal', isRequired: true },
    { documentType: 'BANK_STATEMENT', description: 'Copy of Cancelled Cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
    { documentType: 'EDUCATION_LICENSE', description: 'Copy of Ministry of Education License or Certification', isRequired: true },
  ],
  INTERNATIONAL_EDUCATION_LLC: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID', isRequired: true },
    { documentType: 'DIRECTORS_SHAREHOLDERS_KRA_PIN', description: 'Kenyan Directors and Shareholders KRA PIN Certificates', isRequired: true },
    { documentType: 'CERTIFICATE_OF_INCORPORATION', description: 'Certificate of Incorporation', isRequired: true },
    { documentType: 'COMPANY_KRA_PIN', description: 'Company KRA PIN Certificate (For LTD)', isRequired: true },
    { documentType: 'CR12', description: 'CR12 (Validity: 1 Year)', isRequired: true },
    { documentType: 'PESAPAL_AUTHORIZATION', description: 'Letter Authorizing Entry with Pesapal', isRequired: true },
    { documentType: 'BANK_STATEMENT', description: 'Copy of Cancelled Cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
    { documentType: 'EDUCATION_LICENSE', description: 'Copy of Ministry of Education License or Certification', isRequired: true },
  ],
  PUBLIC_EDUCATION: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID', isRequired: true },
    { documentType: 'DIRECTORS_SHAREHOLDERS_KRA_PIN', description: 'Kenyan Directors and Shareholders KRA PIN Certificates', isRequired: true },
    { documentType: 'CERTIFICATE_OF_REGISTRATION', description: 'Certificate of Registration', isRequired: true },
    { documentType: 'COMPANY_KRA_PIN', description: 'Company KRA PIN Certificate (For LTD)', isRequired: true },
    { documentType: 'BANK_STATEMENT', description: 'Copy of Cancelled Cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
    { documentType: 'COUNTY_AUTHORIZATION', description: 'Contract Form Signed by Authorized Signatory within County Education Department', isRequired: true },
    { documentType: 'EDUCATION_LICENSE', description: 'Copy of Ministry of Education License or Certification', isRequired: true },
  ],
  COOPERATIVE_SOCIETY: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID', isRequired: true },
    { documentType: 'DIRECTORS_SHAREHOLDERS_KRA_PIN', description: 'Kenyan Directors and Shareholders KRA PIN Certificates', isRequired: true },
    { documentType: 'COOP_REGISTRATION', description: 'Certificate of Registration as a Co-operative Society', isRequired: true },
    { documentType: 'ORGANIZATION_KRA_PIN', description: 'Organization\'s KRA PIN Certificate', isRequired: true },
    { documentType: 'CONSTITUTION', description: 'Organization\'s Constitution', isRequired: true },
    { documentType: 'BOARD_MINUTES', description: 'Latest Minutes Electing Board Members / Minutes Showing Election of Current Office Bearers', isRequired: true },
    { documentType: 'PESAPAL_AUTHORIZATION', description: 'Letter Authorizing Entry with Pesapal', isRequired: true },
    { documentType: 'BANK_STATEMENT', description: 'Copy of Cancelled Cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
  ],
  INSURANCE_REINSURANCE: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID', isRequired: true },
    { documentType: 'DIRECTORS_SHAREHOLDERS_KRA_PIN', description: 'Kenyan Directors and Shareholders KRA PIN Certificates', isRequired: true },
    { documentType: 'CERTIFICATE_OF_INCORPORATION', description: 'Certificate of Incorporation', isRequired: true },
    { documentType: 'COMPANY_KRA_PIN', description: 'Company KRA PIN Certificate', isRequired: true },
    { documentType: 'CR12', description: 'Current CR12 (Validity: 1 Year)', isRequired: true },
    { documentType: 'PESAPAL_AUTHORIZATION', description: 'Letter Authorizing Entry with Pesapal', isRequired: true },
    { documentType: 'BANK_STATEMENT', description: 'Copy of Cancelled Cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
    { documentType: 'IRA_LICENSE', description: 'Copy of Institution\'s Annual License from Insurance Regulatory Authority (IRA) or No Objection Letter from IRA', isRequired: true },
  ],
  NGO: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID', isRequired: true },
    { documentType: 'DIRECTORS_SHAREHOLDERS_KRA_PIN', description: 'Kenyan Directors and Shareholders KRA PIN Certificates', isRequired: true },
    { documentType: 'CERTIFICATE_OF_REGISTRATION', description: 'Certificate of Registration', isRequired: true },
    { documentType: 'ORGANIZATION_KRA_PIN', description: 'Organization\'s KRA PIN Certificate', isRequired: true },
    { documentType: 'CONSTITUTION', description: 'Organization\'s Constitution', isRequired: true },
    { documentType: 'PESAPAL_AUTHORIZATION', description: 'Letter Authorizing Entry with Pesapal', isRequired: true },
    { documentType: 'BOARD_MINUTES', description: 'Latest Minutes Electing Board Members / Minutes Showing Election of Current Office Bearers', isRequired: true },
    { documentType: 'BANK_STATEMENT', description: 'Copy of Cancelled Cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
  ],
  EMBASSY_UN_WORLD_BANK: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'Copy of Identification Documents for Signatories, Ambassador, Office Bearers and Operators', isRequired: true },
    { documentType: 'ACCREDITATION_LETTER', description: 'Ministry of Foreign Affairs Letter of Accreditation (For Embassy)', isRequired: true },
    { documentType: 'GOVERNMENT_AGREEMENT', description: 'For International Organizations (e.g., World Bank, UN): Agreement between the Organization and the Government of Kenya', isRequired: true },
    { documentType: 'PESAPAL_AUTHORIZATION', description: 'Letter Authorizing Entry with Pesapal', isRequired: true },
    { documentType: 'INTRODUCTION_LETTER', description: 'Letter of Introduction if the Ambassador/High Commissioner is not the Signatory', isRequired: false },
    { documentType: 'BANK_STATEMENT', description: 'Copy of Cancelled Cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
  ],
  DENOMINATIONAL_CHURCH: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID', isRequired: true },
    { documentType: 'DIRECTORS_SHAREHOLDERS_KRA_PIN', description: 'Kenyan Directors and Shareholders KRA PIN Certificates', isRequired: true },
    { documentType: 'CERTIFICATE_OF_REGISTRATION', description: 'Certificate of Registration', isRequired: true },
    { documentType: 'ORGANIZATION_KRA_PIN', description: 'Organization\'s KRA PIN Certificate', isRequired: true },
    { documentType: 'CONSTITUTION', description: 'Organization\'s Constitution', isRequired: true },
    { documentType: 'BOARD_MINUTES', description: 'Latest Minutes Electing Board Members / Minutes Showing Election of Current Office Bearers', isRequired: true },
    { documentType: 'PESAPAL_AUTHORIZATION', description: 'Letter Authorizing Entry with Pesapal', isRequired: true },
    { documentType: 'BANK_STATEMENT', description: 'Copy of Cancelled Cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
  ],
  PARTNERSHIP_PROFESSIONAL: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID', isRequired: true },
    { documentType: 'PARTNERSHIP_DEED', description: 'Copy of Partnership Deed or Affidavit', isRequired: true },
    { documentType: 'CERTIFICATE_OF_REGISTRATION', description: 'Certified Copy of Certificate of Registration', isRequired: true },
    { documentType: 'DIRECTORS_KRA_PIN', description: 'Kenyan Directors and Shareholders KRA PIN Certificates', isRequired: true },
    { documentType: 'COMPANY_KRA_PIN', description: 'Company KRA PIN Certificate (For LTD)', isRequired: true },
    { documentType: 'CR13', description: 'CR13', isRequired: true },
    { documentType: 'PESAPAL_AUTHORIZATION', description: 'Letter Authorizing Entry with Pesapal', isRequired: true },
    { documentType: 'BANK_STATEMENT', description: 'Copy of Cancelled Cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
  ],
  TRUST: [
    { documentType: 'PP_NEW_CONTRACT', description: 'PP New Contract', isRequired: true },
    { documentType: 'NATIONAL_ID', description: 'National ID, Passport, Alien ID, or Military ID', isRequired: true },
    { documentType: 'TRUST_DEED', description: 'Certificate of Incorporation or Trust Deed (For Unregistered Trusts)', isRequired: true },
    { documentType: 'TRUSTEES_KRA_PIN', description: 'Kenyan Trustees KRA PIN Certificates', isRequired: true },
    { documentType: 'ORGANIZATION_KRA_PIN', description: 'Organization\'s KRA PIN Certificate', isRequired: true },
    { documentType: 'PESAPAL_AUTHORIZATION', description: 'Letter Authorizing Entry into Business with Pesapal', isRequired: true },
    { documentType: 'BANK_STATEMENT', description: 'Copy of Cancelled Cheque or Certified Bank Statements or Certified Letter from Bank', isRequired: true },
  ],
};
