import { OrganizerEntityType, KYCDocumentType } from '@prisma/client';

export interface DocumentRequirement {
  documentType: KYCDocumentType;
  category: 'contract' | 'identity' | 'registration' | 'financial' | 'authorization' | 'industry' | 'organization' | 'special';
  minQuantity: number;
  maxQuantity?: number; // undefined means no limit
  validityPeriodDays?: number; // e.g., 365 for CR12
  isRequired: boolean;
  isConditional: boolean; // If true, only required under certain conditions
  conditionalKey?: string; // Key to check in conditional requirements (e.g., industry type)
  conditionalValue?: string | string[]; // Value(s) that trigger this requirement
  description: string;
  helpText?: string;
}

export interface EntityTypeRequirements {
  entityType: OrganizerEntityType;
  displayName: string;
  category: 'individual' | 'business' | 'organization' | 'government';
  requiresDirectors: boolean;
  requiresShareholders: boolean;
  minDirectors?: number;
  maxDirectorsToCollect?: number; // If > 5, only collect top 5
  documents: DocumentRequirement[];
  conditionalRequirements?: {
    [key: string]: DocumentRequirement[]; // e.g., industry-based requirements
  };
}

/**
 * KYC Requirements Configuration
 * Maps organizer entity types to their required documents
 */
export const KYC_REQUIREMENTS: Record<OrganizerEntityType, EntityTypeRequirements> = {
  [OrganizerEntityType.INDIVIDUAL]: {
    entityType: OrganizerEntityType.INDIVIDUAL,
    displayName: 'Individual',
    category: 'individual',
    requiresDirectors: false,
    requiresShareholders: false,
    documents: [
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'KRA PIN Certificate',
      },
    ],
  },

  [OrganizerEntityType.SOLE_PROPRIETOR]: {
    entityType: OrganizerEntityType.SOLE_PROPRIETOR,
    displayName: 'Sole Proprietor',
    category: 'business',
    requiresDirectors: false,
    requiresShareholders: false,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'KRA PIN Certificate',
      },
      {
        documentType: KYCDocumentType.CERTIFICATE_OF_REGISTRATION,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Certificate of Registration',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
        helpText: 'You can provide either a cancelled cheque, certified bank statement, or certified letter from bank',
      },
    ],
    conditionalRequirements: {
      PRIVATE_HOSPITAL: [
        {
          documentType: KYCDocumentType.MINISTRY_OF_HEALTH_LICENSE,
          category: 'industry',
          minQuantity: 1,
          isRequired: true,
          isConditional: true,
          conditionalKey: 'industry',
          conditionalValue: 'PRIVATE_HOSPITAL',
          description: 'Ministry of Health License or License from KMPDB',
        },
      ],
      E_COMMERCE: [
        {
          documentType: KYCDocumentType.COMPANY_PROFILE,
          category: 'special',
          minQuantity: 1,
          isRequired: true,
          isConditional: true,
          conditionalKey: 'industry',
          conditionalValue: 'E_COMMERCE',
          description: 'Company Profile',
        },
        {
          documentType: KYCDocumentType.ONLINE_LINK,
          category: 'special',
          minQuantity: 1,
          isRequired: true,
          isConditional: true,
          conditionalKey: 'industry',
          conditionalValue: 'E_COMMERCE',
          description: 'Active Online Link',
        },
      ],
    },
  },

  [OrganizerEntityType.PARTNERSHIP]: {
    entityType: OrganizerEntityType.PARTNERSHIP,
    displayName: 'Partnership',
    category: 'business',
    requiresDirectors: true,
    requiresShareholders: false,
    minDirectors: 2,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID (for all partners)',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'KRA PIN certificates for all Kenyan directors/partners',
      },
      {
        documentType: KYCDocumentType.CERTIFICATE_OF_REGISTRATION,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Certificate of Registration',
      },
      {
        documentType: KYCDocumentType.COMPANY_KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Partnership KRA PIN Certificate',
      },
      {
        documentType: KYCDocumentType.LETTER_AUTHORIZING_ENTRY,
        category: 'authorization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Letter Authorizing Entry with Pesapal',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
      },
    ],
  },

  [OrganizerEntityType.LIMITED_LIABILITY_COMPANY]: {
    entityType: OrganizerEntityType.LIMITED_LIABILITY_COMPANY,
    displayName: 'Limited Liability Company',
    category: 'business',
    requiresDirectors: true,
    requiresShareholders: true,
    minDirectors: 1,
    maxDirectorsToCollect: 5,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID (for directors and shareholders)',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'KRA PIN certificates for Kenyan directors and shareholders',
      },
      {
        documentType: KYCDocumentType.CERTIFICATE_OF_INCORPORATION,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Certificate of Incorporation',
      },
      {
        documentType: KYCDocumentType.COMPANY_KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Company KRA PIN Certificate',
      },
      {
        documentType: KYCDocumentType.CR12,
        category: 'registration',
        minQuantity: 1,
        validityPeriodDays: 365,
        isRequired: true,
        isConditional: false,
        description: 'Current CR12 (validity 1 year)',
        helpText: 'CR12 must be less than 1 year old',
      },
      {
        documentType: KYCDocumentType.LETTER_AUTHORIZING_ENTRY,
        category: 'authorization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Letter Authorizing Entry with Pesapal',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
      },
    ],
    conditionalRequirements: {
      PRIVATE_HOSPITAL: [
        {
          documentType: KYCDocumentType.MINISTRY_OF_HEALTH_LICENSE,
          category: 'industry',
          minQuantity: 1,
          isRequired: true,
          isConditional: true,
          conditionalKey: 'industry',
          conditionalValue: 'PRIVATE_HOSPITAL',
          description: 'Ministry of Health License or License from KMPDB',
        },
      ],
      PRIVATE_EDUCATION: [
        {
          documentType: KYCDocumentType.MINISTRY_OF_EDUCATION_LICENSE,
          category: 'industry',
          minQuantity: 1,
          isRequired: true,
          isConditional: true,
          conditionalKey: 'industry',
          conditionalValue: 'PRIVATE_EDUCATION',
          description: 'Copy of Ministry of Education License or Certification',
        },
      ],
      E_COMMERCE: [
        {
          documentType: KYCDocumentType.COMPANY_PROFILE,
          category: 'special',
          minQuantity: 1,
          isRequired: true,
          isConditional: true,
          conditionalKey: 'industry',
          conditionalValue: 'E_COMMERCE',
          description: 'Company Profile',
        },
        {
          documentType: KYCDocumentType.ONLINE_LINK,
          category: 'special',
          minQuantity: 1,
          isRequired: true,
          isConditional: true,
          conditionalKey: 'industry',
          conditionalValue: 'E_COMMERCE',
          description: 'Active Online Link',
        },
      ],
      ENERGY_PETROLEUM: [
        {
          documentType: KYCDocumentType.EPRA_LICENSE,
          category: 'industry',
          minQuantity: 1,
          isRequired: true,
          isConditional: true,
          conditionalKey: 'industry',
          conditionalValue: 'ENERGY_PETROLEUM',
          description: 'EPRA License or Contract from contracting dealership',
        },
      ],
      TOUR_OPERATOR: [
        {
          documentType: KYCDocumentType.TOUR_OPERATOR_LICENSE,
          category: 'industry',
          minQuantity: 1,
          isRequired: true,
          isConditional: true,
          conditionalKey: 'industry',
          conditionalValue: 'TOUR_OPERATOR',
          description: 'Travel and Tour Operator License',
        },
        {
          documentType: KYCDocumentType.TRA_MEMBERSHIP,
          category: 'industry',
          minQuantity: 1,
          isRequired: true,
          isConditional: true,
          conditionalKey: 'industry',
          conditionalValue: 'TOUR_OPERATOR',
          description: 'Membership of TRA',
        },
        {
          documentType: KYCDocumentType.KATO_MEMBERSHIP,
          category: 'industry',
          minQuantity: 1,
          isRequired: true,
          isConditional: true,
          conditionalKey: 'industry',
          conditionalValue: 'TOUR_OPERATOR',
          description: 'Membership in KATO or KATA',
        },
      ],
    },
  },

  [OrganizerEntityType.LIMITED_LIABILITY_PARTNERSHIP]: {
    entityType: OrganizerEntityType.LIMITED_LIABILITY_PARTNERSHIP,
    displayName: 'Limited Liability Partnership',
    category: 'business',
    requiresDirectors: true,
    requiresShareholders: true,
    minDirectors: 1,
    maxDirectorsToCollect: 5,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID (for directors and shareholders)',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'KRA PIN certificates for Kenyan directors and shareholders',
      },
      {
        documentType: KYCDocumentType.CERTIFICATE_OF_INCORPORATION,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Certificate of Incorporation or Certificate of Registration',
      },
      {
        documentType: KYCDocumentType.COMPANY_KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Company KRA PIN Certificate',
      },
      {
        documentType: KYCDocumentType.CR13,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Current CR13',
      },
      {
        documentType: KYCDocumentType.LETTER_AUTHORIZING_ENTRY,
        category: 'authorization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Letter Authorizing Entry with Pesapal',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
      },
    ],
  },

  [OrganizerEntityType.EMPLOYMENT_AGENCY_LLC]: {
    entityType: OrganizerEntityType.EMPLOYMENT_AGENCY_LLC,
    displayName: 'Employment Agency (Limited Liability)',
    category: 'business',
    requiresDirectors: true,
    requiresShareholders: true,
    minDirectors: 1,
    maxDirectorsToCollect: 5,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID (for directors and shareholders)',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'KRA PIN certificates for Kenyan directors and shareholders',
      },
      {
        documentType: KYCDocumentType.CERTIFICATE_OF_INCORPORATION,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Certificate of Incorporation',
      },
      {
        documentType: KYCDocumentType.COMPANY_KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Company KRA PIN Certificate',
      },
      {
        documentType: KYCDocumentType.CR12,
        category: 'registration',
        minQuantity: 1,
        validityPeriodDays: 365,
        isRequired: true,
        isConditional: false,
        description: 'Current CR12 (validity 1 year)',
      },
      {
        documentType: KYCDocumentType.LETTER_AUTHORIZING_ENTRY,
        category: 'authorization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Letter Authorizing Entry with Pesapal',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
      },
      {
        documentType: KYCDocumentType.IRA_LICENSE,
        category: 'industry',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Certified Copy of institution license from National Employment Agency or No Letter from IRA',
      },
    ],
  },

  [OrganizerEntityType.FOREIGN_COMPANY_COMPLIANCE]: {
    entityType: OrganizerEntityType.FOREIGN_COMPANY_COMPLIANCE,
    displayName: 'Foreign Company (Certificate of Compliance)',
    category: 'business',
    requiresDirectors: true,
    requiresShareholders: true,
    minDirectors: 2,
    maxDirectorsToCollect: 5,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 2,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID (at least 2)',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'KRA PIN certificates for Kenyan directors and shareholders',
      },
      {
        documentType: KYCDocumentType.CERTIFICATE_OF_INCORPORATION,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Certificate of Incorporation or Company Certificate of Compliance',
      },
      {
        documentType: KYCDocumentType.COMPANY_KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Company KRA PIN Certificate',
      },
      {
        documentType: KYCDocumentType.CR12,
        category: 'registration',
        minQuantity: 1,
        validityPeriodDays: 365,
        isRequired: true,
        isConditional: false,
        description: 'Current CR12 (validity 1 year)',
      },
      {
        documentType: KYCDocumentType.LETTER_AUTHORIZING_ENTRY,
        category: 'authorization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Letter Authorizing Entry with Pesapal',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
      },
    ],
  },

  // Private Hospitals
  [OrganizerEntityType.PRIVATE_HOSPITAL_SOLE_PROPRIETOR]: {
    entityType: OrganizerEntityType.PRIVATE_HOSPITAL_SOLE_PROPRIETOR,
    displayName: 'Private Hospital (Sole Proprietor)',
    category: 'business',
    requiresDirectors: false,
    requiresShareholders: false,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'KRA PIN Certificate',
      },
      {
        documentType: KYCDocumentType.CERTIFICATE_OF_REGISTRATION,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Certificate of Registration',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
      },
      {
        documentType: KYCDocumentType.MINISTRY_OF_HEALTH_LICENSE,
        category: 'industry',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Ministry of Health License or License from KMPDB',
      },
    ],
  },

  [OrganizerEntityType.PRIVATE_HOSPITAL_LLC]: {
    entityType: OrganizerEntityType.PRIVATE_HOSPITAL_LLC,
    displayName: 'Private Hospital (Limited Liability)',
    category: 'business',
    requiresDirectors: true,
    requiresShareholders: true,
    minDirectors: 1,
    maxDirectorsToCollect: 5,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID (for directors and shareholders)',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'KRA PIN certificates for Kenyan directors and shareholders',
      },
      {
        documentType: KYCDocumentType.CERTIFICATE_OF_INCORPORATION,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Certificate of Incorporation',
      },
      {
        documentType: KYCDocumentType.COMPANY_KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Company KRA PIN Certificate',
      },
      {
        documentType: KYCDocumentType.CR12,
        category: 'registration',
        minQuantity: 1,
        validityPeriodDays: 365,
        isRequired: true,
        isConditional: false,
        description: 'Current CR12 (validity 1 year)',
      },
      {
        documentType: KYCDocumentType.LETTER_AUTHORIZING_ENTRY,
        category: 'authorization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Letter Authorizing Entry with Pesapal',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
      },
      {
        documentType: KYCDocumentType.MINISTRY_OF_HEALTH_LICENSE,
        category: 'industry',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Ministry of Health License or License from KMPDB',
      },
    ],
  },

  [OrganizerEntityType.PUBLIC_HOSPITAL]: {
    entityType: OrganizerEntityType.PUBLIC_HOSPITAL,
    displayName: 'Public Hospital',
    category: 'government',
    requiresDirectors: false,
    requiresShareholders: false,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 2,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID (at least 2 for signatories)',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Signatories KRA PIN',
      },
      {
        documentType: KYCDocumentType.CERTIFICATE_OF_REGISTRATION,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Certificate of Registration',
      },
      {
        documentType: KYCDocumentType.COMPANY_KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Hospital KRA PIN Certificate',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
      },
      {
        documentType: KYCDocumentType.LETTER_AUTHORIZING_ENTRY,
        category: 'authorization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Letter Authorizing Entry with Pesapal',
      },
      {
        documentType: KYCDocumentType.COUNTY_CONTRACT_FORM,
        category: 'organization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Contract form signed by authorized signatory within County health department',
      },
    ],
  },

  // Education Institutions
  [OrganizerEntityType.PRIVATE_EDUCATION_SOLE_PROPRIETOR]: {
    entityType: OrganizerEntityType.PRIVATE_EDUCATION_SOLE_PROPRIETOR,
    displayName: 'Private Education Institution (Sole Proprietor)',
    category: 'business',
    requiresDirectors: false,
    requiresShareholders: false,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'KRA PIN Certificate',
      },
      {
        documentType: KYCDocumentType.CERTIFICATE_OF_REGISTRATION,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Certificate of Registration',
      },
      {
        documentType: KYCDocumentType.COMPANY_KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'School KRA PIN Certificate',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
      },
      {
        documentType: KYCDocumentType.MINISTRY_OF_EDUCATION_LICENSE,
        category: 'industry',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Copy of Ministry of Education License or Certification',
      },
    ],
  },

  [OrganizerEntityType.PRIVATE_EDUCATION_LLC]: {
    entityType: OrganizerEntityType.PRIVATE_EDUCATION_LLC,
    displayName: 'Private Education Institution (Limited Liability)',
    category: 'business',
    requiresDirectors: true,
    requiresShareholders: true,
    minDirectors: 1,
    maxDirectorsToCollect: 5,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID (for directors and shareholders)',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'KRA PIN certificates for Kenyan directors and shareholders',
      },
      {
        documentType: KYCDocumentType.CERTIFICATE_OF_INCORPORATION,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Certificate of Incorporation',
      },
      {
        documentType: KYCDocumentType.COMPANY_KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Company KRA PIN Certificate',
      },
      {
        documentType: KYCDocumentType.CR12,
        category: 'registration',
        minQuantity: 1,
        validityPeriodDays: 365,
        isRequired: true,
        isConditional: false,
        description: 'Current CR12 (validity 1 year)',
      },
      {
        documentType: KYCDocumentType.LETTER_AUTHORIZING_ENTRY,
        category: 'authorization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Letter Authorizing Entry with Pesapal',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
      },
      {
        documentType: KYCDocumentType.MINISTRY_OF_EDUCATION_LICENSE,
        category: 'industry',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Copy of Ministry of Education License or Certification',
      },
    ],
  },

  [OrganizerEntityType.INTERNATIONAL_EDUCATION_LLC]: {
    entityType: OrganizerEntityType.INTERNATIONAL_EDUCATION_LLC,
    displayName: 'International Education Institution (Limited Liability)',
    category: 'business',
    requiresDirectors: true,
    requiresShareholders: true,
    minDirectors: 1,
    maxDirectorsToCollect: 5,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID (for directors and shareholders)',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'KRA PIN certificates for Kenyan directors and shareholders',
      },
      {
        documentType: KYCDocumentType.CERTIFICATE_OF_INCORPORATION,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Certificate of Incorporation',
      },
      {
        documentType: KYCDocumentType.COMPANY_KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Company KRA PIN Certificate (For LTD)',
      },
      {
        documentType: KYCDocumentType.CR12,
        category: 'registration',
        minQuantity: 1,
        validityPeriodDays: 365,
        isRequired: true,
        isConditional: false,
        description: 'CR12 (validity 1 year)',
      },
      {
        documentType: KYCDocumentType.LETTER_AUTHORIZING_ENTRY,
        category: 'authorization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Letter Authorizing Entry with Pesapal',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
      },
      {
        documentType: KYCDocumentType.MINISTRY_OF_EDUCATION_LICENSE,
        category: 'industry',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Copy of Ministry of Education License or Certification',
      },
    ],
  },

  [OrganizerEntityType.PUBLIC_EDUCATION]: {
    entityType: OrganizerEntityType.PUBLIC_EDUCATION,
    displayName: 'Public Education Institution',
    category: 'government',
    requiresDirectors: false,
    requiresShareholders: false,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'KRA PIN certificates for directors and shareholders',
      },
      {
        documentType: KYCDocumentType.CERTIFICATE_OF_REGISTRATION,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Certificate of Registration',
      },
      {
        documentType: KYCDocumentType.COMPANY_KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Company KRA PIN Certificate (For LTD)',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
      },
      {
        documentType: KYCDocumentType.COUNTY_CONTRACT_FORM,
        category: 'organization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Contract form signed by authorized signatory within County Education Department',
      },
      {
        documentType: KYCDocumentType.MINISTRY_OF_EDUCATION_LICENSE,
        category: 'industry',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Copy of Ministry of Education License or Certification',
      },
    ],
  },

  [OrganizerEntityType.COOPERATIVE_SOCIETY]: {
    entityType: OrganizerEntityType.COOPERATIVE_SOCIETY,
    displayName: 'Co-operative Society',
    category: 'organization',
    requiresDirectors: true,
    requiresShareholders: false,
    minDirectors: 1,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'KRA PIN certificates for directors and shareholders',
      },
      {
        documentType: KYCDocumentType.CERTIFICATE_OF_REGISTRATION,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Certificate of Registration as a Co-operative society',
      },
      {
        documentType: KYCDocumentType.COMPANY_KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Organization\'s KRA PIN Certificate',
      },
      {
        documentType: KYCDocumentType.ORGANIZATION_CONSTITUTION,
        category: 'organization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Organization\'s Constitution',
      },
      {
        documentType: KYCDocumentType.BOARD_ELECTION_MINUTES,
        category: 'organization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Latest minutes electing board members / Minutes showing election of current office bearers',
      },
      {
        documentType: KYCDocumentType.LETTER_AUTHORIZING_ENTRY,
        category: 'authorization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Letter Authorizing Entry with Pesapal',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
      },
    ],
  },

  [OrganizerEntityType.INSURANCE_REINSURANCE]: {
    entityType: OrganizerEntityType.INSURANCE_REINSURANCE,
    displayName: 'Insurance/Reinsurance Company',
    category: 'business',
    requiresDirectors: true,
    requiresShareholders: true,
    minDirectors: 1,
    maxDirectorsToCollect: 5,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID (for directors and shareholders)',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'KRA PIN certificates for Kenyan directors and shareholders',
      },
      {
        documentType: KYCDocumentType.CERTIFICATE_OF_INCORPORATION,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Certificate of Incorporation',
      },
      {
        documentType: KYCDocumentType.COMPANY_KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Company KRA PIN Certificate',
      },
      {
        documentType: KYCDocumentType.CR12,
        category: 'registration',
        minQuantity: 1,
        validityPeriodDays: 365,
        isRequired: true,
        isConditional: false,
        description: 'Current CR12 (validity 1 year)',
      },
      {
        documentType: KYCDocumentType.LETTER_AUTHORIZING_ENTRY,
        category: 'authorization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Letter Authorizing Entry with Pesapal',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
      },
      {
        documentType: KYCDocumentType.IRA_LICENSE,
        category: 'industry',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Copy of institution annual license from Insurance Regulatory Authority (IRA) or No Letter from IRA',
      },
    ],
  },

  [OrganizerEntityType.NGO]: {
    entityType: OrganizerEntityType.NGO,
    displayName: 'Non-Governmental Organization (NGO)',
    category: 'organization',
    requiresDirectors: true,
    requiresShareholders: false,
    minDirectors: 1,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'KRA PIN certificates for directors and shareholders',
      },
      {
        documentType: KYCDocumentType.CERTIFICATE_OF_REGISTRATION,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Certificate of Registration',
      },
      {
        documentType: KYCDocumentType.COMPANY_KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Organization\'s KRA PIN Certificate',
      },
      {
        documentType: KYCDocumentType.ORGANIZATION_CONSTITUTION,
        category: 'organization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Organization\'s Constitution',
      },
      {
        documentType: KYCDocumentType.LETTER_AUTHORIZING_ENTRY,
        category: 'authorization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Letter Authorizing Entry with Pesapal',
      },
      {
        documentType: KYCDocumentType.BOARD_ELECTION_MINUTES,
        category: 'organization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Latest minutes electing board members / Minutes showing election of current office bearers',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
      },
    ],
  },

  [OrganizerEntityType.EMBASSY_UN_WORLD_BANK]: {
    entityType: OrganizerEntityType.EMBASSY_UN_WORLD_BANK,
    displayName: 'Embassy/UN/World Bank',
    category: 'government',
    requiresDirectors: false,
    requiresShareholders: false,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Copy of identification documents for signatories, ambassador, office bearers and operators (National ID, Passport, Alien ID, Military ID)',
      },
      {
        documentType: KYCDocumentType.ACCREDITATION_LETTER,
        category: 'organization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Ministry of Affairs letter of accreditation for embassy',
      },
      {
        documentType: KYCDocumentType.AGREEMENT_LETTER,
        category: 'organization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'For international organizations like World Bank, UN, an agreement between them and Government of Kenya',
      },
      {
        documentType: KYCDocumentType.LETTER_AUTHORIZING_ENTRY,
        category: 'authorization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Letter Authorizing Entry with Pesapal',
      },
      {
        documentType: KYCDocumentType.LETTER_OF_INTRODUCTION,
        category: 'organization',
        minQuantity: 1,
        isRequired: false,
        isConditional: true,
        conditionalKey: 'signatory',
        conditionalValue: 'not_ambassador',
        description: 'Letter of introduction if the ambassador/high commissioner is not the signatory',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
      },
    ],
  },

  [OrganizerEntityType.DENOMINATIONAL_CHURCH]: {
    entityType: OrganizerEntityType.DENOMINATIONAL_CHURCH,
    displayName: 'Denominational Church',
    category: 'organization',
    requiresDirectors: true,
    requiresShareholders: false,
    minDirectors: 1,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'KRA PIN certificates for directors and shareholders',
      },
      {
        documentType: KYCDocumentType.CERTIFICATE_OF_REGISTRATION,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Certificate of Registration',
      },
      {
        documentType: KYCDocumentType.COMPANY_KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Organization\'s KRA PIN Certificate',
      },
      {
        documentType: KYCDocumentType.ORGANIZATION_CONSTITUTION,
        category: 'organization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Organization\'s Constitution',
      },
      {
        documentType: KYCDocumentType.BOARD_ELECTION_MINUTES,
        category: 'organization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Latest minutes electing board members / Minutes showing election of current office bearers',
      },
      {
        documentType: KYCDocumentType.LETTER_AUTHORIZING_ENTRY,
        category: 'authorization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Letter Authorizing Entry with Pesapal',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
      },
    ],
  },

  [OrganizerEntityType.PARTNERSHIP_PROFESSIONAL]: {
    entityType: OrganizerEntityType.PARTNERSHIP_PROFESSIONAL,
    displayName: 'Partnership (Professional)',
    category: 'business',
    requiresDirectors: true,
    requiresShareholders: false,
    minDirectors: 2,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID',
      },
      {
        documentType: KYCDocumentType.PARTNERSHIP_DEED,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Copy of Partnership Deed or Affidavit',
      },
      {
        documentType: KYCDocumentType.CERTIFICATE_OF_REGISTRATION,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'A Certified Copy of Certificate of Registration',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'KRA PIN certificates for Kenyan directors and shareholders',
      },
      {
        documentType: KYCDocumentType.COMPANY_KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Company KRA PIN Certificate (For LTD)',
      },
      {
        documentType: KYCDocumentType.CR13,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'CR13',
      },
      {
        documentType: KYCDocumentType.LETTER_AUTHORIZING_ENTRY,
        category: 'authorization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Letter Authorizing Entry with Pesapal',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
      },
    ],
  },

  [OrganizerEntityType.TRUST]: {
    entityType: OrganizerEntityType.TRUST,
    displayName: 'Trust',
    category: 'organization',
    requiresDirectors: true,
    requiresShareholders: false,
    minDirectors: 2,
    documents: [
      {
        documentType: KYCDocumentType.PP_NEW_CONTRACT,
        category: 'contract',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'PP New Contract',
      },
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID',
      },
      {
        documentType: KYCDocumentType.CERTIFICATE_OF_INCORPORATION,
        category: 'registration',
        minQuantity: 1,
        isRequired: false,
        isConditional: true,
        conditionalKey: 'trust_type',
        conditionalValue: 'registered',
        description: 'Certificate of Incorporation (for registered trusts)',
      },
      {
        documentType: KYCDocumentType.TRUST_DEED,
        category: 'organization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Trust Deed (for unregistered trusts)',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Kenyan Trustees KRA PIN certificates',
      },
      {
        documentType: KYCDocumentType.COMPANY_KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Organization\'s KRA PIN Certificate',
      },
      {
        documentType: KYCDocumentType.LETTER_AUTHORIZING_ENTRY,
        category: 'authorization',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Letter Authorizing entry into business with Pesapal',
      },
      {
        documentType: KYCDocumentType.BANK_STATEMENT,
        category: 'financial',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'Cancelled cheque, Certified Bank statements, or Certified Letter from Bank',
      },
    ],
  },

  [OrganizerEntityType.OTHER]: {
    entityType: OrganizerEntityType.OTHER,
    displayName: 'Other',
    category: 'business',
    requiresDirectors: false,
    requiresShareholders: false,
    documents: [
      {
        documentType: KYCDocumentType.NATIONAL_ID,
        category: 'identity',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'National ID, Passport, Alien ID, or Military ID',
      },
      {
        documentType: KYCDocumentType.KRA_PIN,
        category: 'registration',
        minQuantity: 1,
        isRequired: true,
        isConditional: false,
        description: 'KRA PIN Certificate',
      },
    ],
  },
};

/**
 * Get requirements for a specific entity type
 */
export function getEntityRequirements(entityType: OrganizerEntityType): EntityTypeRequirements | null {
  return KYC_REQUIREMENTS[entityType] || null;
}

/**
 * Get all required documents for an entity type, including conditionals based on industry
 */
export function getRequiredDocuments(
  entityType: OrganizerEntityType,
  industry?: string,
): DocumentRequirement[] {
  const requirements = getEntityRequirements(entityType);
  if (!requirements) return [];

  const documents = [...requirements.documents];

  // Add conditional requirements if industry is provided
  if (industry && requirements.conditionalRequirements) {
    const conditionalDocs = requirements.conditionalRequirements[industry];
    if (conditionalDocs) {
      documents.push(...conditionalDocs);
    }
  }

  return documents;
}

/**
 * Check if an entity type requires directors/shareholders
 */
export function requiresDirectorsOrShareholders(entityType: OrganizerEntityType): {
  requiresDirectors: boolean;
  requiresShareholders: boolean;
  minDirectors?: number;
  maxDirectorsToCollect?: number;
} {
  const requirements = getEntityRequirements(entityType);
  if (!requirements) {
    return { requiresDirectors: false, requiresShareholders: false };
  }

  return {
    requiresDirectors: requirements.requiresDirectors,
    requiresShareholders: requirements.requiresShareholders,
    minDirectors: requirements.minDirectors,
    maxDirectorsToCollect: requirements.maxDirectorsToCollect,
  };
}

